//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MyConfiguration.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_TOOLBAR_BASEELEMENT         117
#define IDS_TOOLBAR_ADVANCEELEMENT      118
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MyConfigurationTYPE         130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDB_BITMAP1                     316
#define IDS_FILES_VIEW                  1154
#define IDS_EDITS_VIEW                  1155
#define IDS_BASE_ELEMENT_VIEW           1156
#define IDS_ADVANCE_ELEMENT_VIEW        1157
#define IDS_OUTPUT_WND                  1158
#define IDS_PROPERTIES_WND              1159
#define IDB_FILES                       5000
#define ID_TOOLBOX_NEWFILE              5001
#define ID_TOOLBOX_OPENFILE             5002
#define ID_TOOLBOX_SAVEFILE             5003
#define ID_TOOLBOX_PRINTFILE            5004
#define ID_TOOLBOX_PRINTVIEWFILE        5005
#define ID_TOOLBOX_HELP                 5006
#define IDB_EDITS                       6000
#define ID_TOOLBOX_ARROW                6001
#define ID_TOOLBOX_LOCK                 6002
#define ID_TOOLBOX_CUT                  6003
#define ID_TOOLBOX_COPY                 6004
#define ID_TOOLBOX_PASTE                6005
#define ID_TOOLBOX_MORE                 6006
#define ID_TOOLBOX_DELETE               6007
#define ID_TOOLBOX_UNDO                 6008
#define ID_TOOLBOX_REDO                 6009
#define ID_TOOLBOX_BRINGTOTOP           6010
#define ID_TOOLBOX_BRINGTOBOTTOM        6011
#define ID_TOOLBOX_LEFT                 6012
#define ID_TOOLBOX_RIGHT                6013
#define ID_TOOLBOX_TOP                  6014
#define ID_TOOLBOX_BOTTOM               6015
#define ID_TOOLBOX_FIT                  6016
#define ID_TOOLBOX_SAME                 6017
#define ID_TOOLBOX_WIDTH_SAME           6018
#define ID_TOOLBOX_HEIGHT_SAME          6019
#define ID_TOOLBOX_EQUEL_DISTANCE       6020
#define ID_TOOLBOX_INCREASE             6021
#define ID_TOOLBOX_DECREASE             6022
#define ID_TOOLBOX_ROTATE_90            6023
#define ID_TOOLBOX_ROTATE90             6024
#define ID_TOOLBOX_MACRO                6025
#define ID_TOOLBOX_SYMBOL               6026
#define ID_TOOLBOX_GROUP                6027
#define ID_TOOLBOX_UNGROUP              6028
#define IDB_BASEELEMENT                 10000
#define ID_TOOLBOX_BACKGROUND           10001
#define ID_TOOLBOX_LINE                 10002
#define ID_TOOLBOX_RECT                 10003
#define ID_TOOLBOX_ELLIPSE              10004
#define ID_TOOLBOX_POLYGON              10005
#define ID_TOOLBOX_ARC                  10006
#define ID_TOOLBOX_TEXT                 10007
#define IDB_ADVANCEELEMENT              20000
#define ID_TOOLBOX_ANALOG               20001
#define ID_TOOLBOX_DIGITAL              20002
#define ID_TOOLBOX_PICTURE              20003
#define ID_TOOLBOX_CAMERA               20004
#define ID_TOOLBOX_SHOWTIME             20005
#define ID_TOOLBOX_BUTTON               20006
#define ID_TOOLBOX_REAL_ALARMLIST       20007
#define ID_TOOLBOX_REAL_DATALIST        20008
#define ID_TOOLBOX_REAL_DATACURVE       20009
#define ID_TOOLBOX_REAL_DATACOLUMN      20010
#define ID_TOOLBOX_REAL_DATAPLANT       20011
#define ID_TOOLBOX_REAL_DATACIRCLE      20012
#define ID_TOOLBOX_HIS_DATALIST         20013
#define ID_TOOLBOX_HIS_DATACURVE        20014
#define ID_TOOLBOX_HIS_DATACOLUMN       20015
#define ID_TOOLBOX_HIS_DATAPLANT        20016
#define ID_TOOLBOX_HIS_DATACIRCLE       20017
#define ID_TOOLBOX_HIS_CHOOSETIME       20018
#define ID_Menu                         32771
#define ID_FILE_TOOL_BAR                32773
#define ID_EDIT_TOOL_BAR                32774
#define ID_VIEW_TOOL_BAR                32775
#define ID_BASEELEMENT_TOOL_BAR         32776
#define ID_ADVANCEELEMENT_TOOL_BAR      32777
#define BER_FUNCTION                    32778
#define ID_PROP_TOOL_BAR                32779
#define ID_OUTPUT_TOOL_BAR              32780

#define ID_PROP_BACKGROUND_NAME         40001
#define ID_PROP_BACKGROUND_X			40002
#define ID_PROP_BACKGROUND_Y			40003
#define ID_PROP_BACKGROUND_COLOR		40004
#define ID_PROP_IS_BACKGROUND_PIC		40005
#define ID_PROP_BACKGROUND_PIC			40006
#define ID_PROP_BACKGROUND_SHOWTYPE		40007
#define ID_PROP_LINE_NAME				41001
#define ID_PROP_LINE_STARTX				41002
#define ID_PROP_LINE_STARTY				41003
#define ID_PROP_LINE_ENDX				41004
#define ID_PROP_LINE_ENDY				41005
#define ID_PROP_LINE_COLOR				41006
#define ID_PROP_LINE_TYPE				41007
#define ID_PROP_LINE_WIDTH				41008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        317
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
